    language: python

    python:
      - "3.6"

    services:
      - mysql

    env:
      -DJANGO=2.1.5 DB=mysql

    install:
      # we need a command to install our dependencies here, this is in the process of being changed i think?
      - pip install django

    before_script:
      - mysql -e 'create database test;' -u root
      -
    script:
      - python manage.py test