    language: python

    python:
      - "3.6"

    services:
      - mysql

    env:
      -DJANGO=2.1.5 DB=mysql

    install:
      # we need a command to install our dependencies here, this is in the process of being changed i think?
      - pip install django
      - pip install coverage
      - pip install django-material
      - pip install -r requirements.txt
      - pip install django-viewflow
      - pip install redgreenunittest
      - pip install django-octicons
      - pip install behave_django
    before_script:
      - mysql -e 'create database test;' -u root
      -
    script:
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py test
      - coverage run --source='.' manage.py test
      - coverage report