# Generated by Django 2.1.5 on 2019-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.IntegerField(),
        ),
    ]
