# Generated by Django 2.1.5 on 2019-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('bday', models.DateField()),
                ('doc_notes', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('today_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
